// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cprestegard_sp2026_assignment3.Data;

#nullable disable

namespace cprestegard_sp2026_assignment3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cprestegard_sp2026_assignment3.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImdbUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            Age = 87,
                            Gender = "Male",
                            ImdbUrl = "https://www.imdb.com/name/nm0000151/",
                            Name = "Morgan Freeman",
                            PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTc0MDMyMzI2OF5BMl5BanBnXkFtZTcwMzM2OTk1MQ@@._V1_UX214_CR0,0,214,317_AL_.jpg"
                        },
                        new
                        {
                            ActorId = 2,
                            Age = 66,
                            Gender = "Male",
                            ImdbUrl = "https://www.imdb.com/name/nm0000209/",
                            Name = "Tim Robbins",
                            PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTI1OTYxNzAxOF5BMl5BanBnXkFtZTYwNTE5ODI4._V1_UY317_CR16,0,214,317_AL_.jpg"
                        },
                        new
                        {
                            ActorId = 3,
                            Age = 51,
                            Gender = "Male",
                            ImdbUrl = "https://www.imdb.com/name/nm0000288/",
                            Name = "Christian Bale",
                            PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTkxMzk4MjQ4MF5BMl5BanBnXkFtZTcwMzExODQxOA@@._V1_UX214_CR0,0,214,317_AL_.jpg"
                        },
                        new
                        {
                            ActorId = 4,
                            Age = 28,
                            Gender = "Male",
                            ImdbUrl = "https://www.imdb.com/name/nm0005132/",
                            Name = "Heath Ledger",
                            PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTI2NTY0NzA4MF5BMl5BanBnXkFtZTYwMjE1MDE0._V1_UY317_CR17,0,214,317_AL_.jpg"
                        },
                        new
                        {
                            ActorId = 5,
                            Age = 50,
                            Gender = "Male",
                            ImdbUrl = "https://www.imdb.com/name/nm0000138/",
                            Name = "Leonardo DiCaprio",
                            PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMjI0MTg3MzI0M15BMl5BanBnXkFtZTcwMzQyODU2Mw@@._V1_UY317_CR10,0,214,317_AL_.jpg"
                        },
                        new
                        {
                            ActorId = 6,
                            Age = 49,
                            Gender = "Female",
                            ImdbUrl = "https://www.imdb.com/name/nm0182839/",
                            Name = "Marion Cotillard",
                            PhotoUrl = "https://m.media-amazon.com/images/M/MV5BNzJhOWY4YjAtYTMzZS00MTdmLTk5NjQtMDMyNzBlZDYxYjk1XkEyXkFqcGdeQXVyMTMxMTIwMTE2._V1_UY317_CR106,0,214,317_AL_.jpg"
                        },
                        new
                        {
                            ActorId = 7,
                            Age = 71,
                            Gender = "Male",
                            ImdbUrl = "https://www.imdb.com/name/nm0000237/",
                            Name = "John Travolta",
                            PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTUwNjQ0ODkxN15BMl5BanBnXkFtZTcwODE4MzI5OA@@._V1_UY317_CR6,0,214,317_AL_.jpg"
                        },
                        new
                        {
                            ActorId = 8,
                            Age = 54,
                            Gender = "Female",
                            ImdbUrl = "https://www.imdb.com/name/nm0000235/",
                            Name = "Uma Thurman",
                            PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMjMwNjEzNjQ2Nl5BMl5BanBnXkFtZTcwODQzNTQxNA@@._V1_UY317_CR21,0,214,317_AL_.jpg"
                        },
                        new
                        {
                            ActorId = 9,
                            Age = 68,
                            Gender = "Male",
                            ImdbUrl = "https://www.imdb.com/name/nm0000158/",
                            Name = "Tom Hanks",
                            PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTQ2MjMwNDA3Nl5BMl5BanBnXkFtZTcwMTA2NDY3NQ@@._V1_UY317_CR2,0,214,317_AL_.jpg"
                        },
                        new
                        {
                            ActorId = 10,
                            Age = 58,
                            Gender = "Female",
                            ImdbUrl = "https://www.imdb.com/name/nm0000705/",
                            Name = "Robin Wright",
                            PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTQwMDg1NjA4NV5BMl5BanBnXkFtZTcwMTMxMjA5Nw@@._V1_UY317_CR14,0,214,317_AL_.jpg"
                        });
                });

            modelBuilder.Entity("cprestegard_sp2026_assignment3.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImdbUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Genre = "Drama",
                            ImdbUrl = "https://www.imdb.com/title/tt0111161/",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            MovieId = 2,
                            Genre = "Action",
                            ImdbUrl = "https://www.imdb.com/title/tt0468569/",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 3,
                            Genre = "Sci-Fi",
                            ImdbUrl = "https://www.imdb.com/title/tt1375666/",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 4,
                            Genre = "Crime",
                            ImdbUrl = "https://www.imdb.com/title/tt0110912/",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
                            ReleaseYear = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            MovieId = 5,
                            Genre = "Drama",
                            ImdbUrl = "https://www.imdb.com/title/tt0109830/",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
                            ReleaseYear = 1994,
                            Title = "Forrest Gump"
                        });
                });

            modelBuilder.Entity("cprestegard_sp2026_assignment3.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieActorId"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("MovieActorId");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieActorId = 1,
                            ActorId = 1,
                            CharacterName = "Ellis Boyd 'Red' Redding",
                            MovieId = 1
                        },
                        new
                        {
                            MovieActorId = 2,
                            ActorId = 2,
                            CharacterName = "Andy Dufresne",
                            MovieId = 1
                        },
                        new
                        {
                            MovieActorId = 3,
                            ActorId = 3,
                            CharacterName = "Bruce Wayne / Batman",
                            MovieId = 2
                        },
                        new
                        {
                            MovieActorId = 4,
                            ActorId = 4,
                            CharacterName = "Joker",
                            MovieId = 2
                        },
                        new
                        {
                            MovieActorId = 5,
                            ActorId = 1,
                            CharacterName = "Lucius Fox",
                            MovieId = 2
                        },
                        new
                        {
                            MovieActorId = 6,
                            ActorId = 5,
                            CharacterName = "Dom Cobb",
                            MovieId = 3
                        },
                        new
                        {
                            MovieActorId = 7,
                            ActorId = 6,
                            CharacterName = "Mal Cobb",
                            MovieId = 3
                        },
                        new
                        {
                            MovieActorId = 8,
                            ActorId = 7,
                            CharacterName = "Vincent Vega",
                            MovieId = 4
                        },
                        new
                        {
                            MovieActorId = 9,
                            ActorId = 8,
                            CharacterName = "Mia Wallace",
                            MovieId = 4
                        },
                        new
                        {
                            MovieActorId = 10,
                            ActorId = 9,
                            CharacterName = "Forrest Gump",
                            MovieId = 5
                        },
                        new
                        {
                            MovieActorId = 11,
                            ActorId = 10,
                            CharacterName = "Jenny Curran",
                            MovieId = 5
                        });
                });

            modelBuilder.Entity("cprestegard_sp2026_assignment3.Models.MovieActor", b =>
                {
                    b.HasOne("cprestegard_sp2026_assignment3.Models.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cprestegard_sp2026_assignment3.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("cprestegard_sp2026_assignment3.Models.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("cprestegard_sp2026_assignment3.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");
                });
#pragma warning restore 612, 618
        }
    }
}
